[versions]
kotlin = "2.4.0"
ktor = "3.5.1"
logback = "1.5.35"
flyway = "12.11.0"
postgresql-driver = "42.7.13"
jooq = "3.21.6"
hikari-cp = "7.1.0"
testcontainers = "2.0.5"
kotest = "6.2.4"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-di = { module = "io.ktor:ktor-server-di" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
postgresql-driver = { module = "org.postgresql:postgresql", version.ref = "postgresql-driver" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
jooq-core = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
testcontainers-postgres = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-ktor = { module = "io.kotest:kotest-assertions-ktor", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
